# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_playlist_playlist_song'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayList_Song',
            new_name='PlayListSong',
        ),
    ]
