# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-01 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20160702_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyricist',
            field=models.CharField(default=b'', max_length=250),
        ),
        migrations.AddField(
            model_name='song',
            name='lyrics_file',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='song',
            name='singers',
            field=models.CharField(default=b'', max_length=250),
        ),
    ]
