# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_auto_20170425_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='language',
            field=models.CharField(max_length=1000),
        ),
    ]
