# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0016_auto_20170425_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyrics',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Language'),
        ),
    ]
