# This is a basic workflow to help you get started with Actions

name: Docker Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
           fetch-depth: 0
           
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
           python-version: '3.9'
           
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}
          
       - name: Install dependecy
         run: |
           echo "dep"
           pip install -r requirements.txt
           
           
        - name: docker build
          run: |
            export DOCKER_BUILDKIT=1
            DOCKER_BUILDKIT=1 docker build -t MusicBox:1.0 --build-arg BUILDKIT_INLINE_CACHE=1 \
            --progress=plain -f Conatinerfile .




