apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: musicbox
  template:
    metadata:
      labels:
        app: musicbox
    spec:
      containers:
      - name: musicbox
        image: basivireddy/musicbox:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: musicbox
  labels:
    app: musicbox
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: musicbox

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: hostlessendpoint
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: musicbox
          servicePort: 80
